spring:
  application:
    name: ui-microservice
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB    
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-microservice:1111/eureka/
server:
  port: 8080